#!/bin/usr/env python3
import sys

from pyssianutils.utils import SUBPARSERS, MAINS, create_parser

# These imports are required, to populate the SUBPARSERS and the MAINS variables
import pyssianutils.initialize
import pyssianutils.input
import pyssianutils.print


if __name__ == '__main__': 
    parser = create_parser()
    args = parser.parse_args()

    if args.command is None: 
        parser.print_help(sys.stderr)
    else:
        kwargs = dict(args._get_kwargs())
        command = kwargs.pop('command')
        
        if kwargs:
            MAINS[command](**kwargs)
        else:
            MAINS[command]()
